CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (name) VALUES
    ('CUSTOMER'),
    ('MANAGER'),
    ('ADMIN');

ALTER TABLE IF EXISTS users
DROP COLUMN IF EXISTS role;

ALTER TABLE IF EXISTS users
ADD COLUMN IF NOT EXISTS role_id INTEGER NOT NULL DEFAULT 1 REFERENCES roles(id);